"""create ingestion domain tables

Revision ID: 9c9ef8fe2981
Revises: 
Create Date: 2026-09-23 11:31:21.540047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c9ef8fe2981'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('repositories',
  sa.Column('id', sa.BigInteger(), nullable=False),
  sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
  sa.Column('owner', sa.String(length=255), nullable=False),
  sa.Column('full_name', sa.String(length=255), nullable=False),
  sa.Column('default_branch', sa.String(length=255), nullable=False),
  sa.Column('html_url', sa.String(length=255), nullable=False),
  sa.Column('is_private', sa.Boolean(), nullable=False),
  sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
  sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
  sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
  sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
  sa.PrimaryKeyConstraint('id'),
  sa.UniqueConstraint('github_repo_id')
  )
  op.create_table('github_events',
  sa.Column('id', sa.BigInteger(), nullable=False),
  sa.Column('github_delivery_id', sa.String(length=255), nullable=False),
  sa.Column('event_type', sa.String(length=100), nullable=False),
  sa.Column('action', sa.String(length=100), nullable=True),
  sa.Column('repository_id', sa.BigInteger(), nullable=True),
  sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
  sa.Column('status', sa.String(length=30), nullable=False),
  sa.Column('error_message', sa.Text(), nullable=True),
  sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
  sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
  sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
  sa.PrimaryKeyConstraint('id'),
  sa.UniqueConstraint('github_delivery_id')
  )
  op.create_table('pull_requests',
  sa.Column('id', sa.BigInteger(), nullable=False),
  sa.Column('repository_id', sa.BigInteger(), nullable=False),
  sa.Column('github_pr_id', sa.BigInteger(), nullable=False),
  sa.Column('number', sa.Integer(), nullable=False),
  sa.Column('title', sa.Text(), nullable=False),
  sa.Column('body', sa.Text(), nullable=True),
  sa.Column('author_github_id', sa.BigInteger(), nullable=True),
  sa.Column('author_login', sa.String(length=255), nullable=True),
  sa.Column('base_branch', sa.String(length=255), nullable=False),
  sa.Column('head_branch', sa.String(length=255), nullable=False),
  sa.Column('base_sha', sa.String(length=40), nullable=False),
  sa.Column('head_sha', sa.String(length=40), nullable=False),
  sa.Column('status', sa.String(length=30), nullable=False),
  sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
  sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
  sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
  sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
  sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
  sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
  sa.PrimaryKeyConstraint('id'),
  sa.UniqueConstraint('repository_id', 'github_pr_id')
  )
  op.create_table('pull_request_files',
  sa.Column('id', sa.BigInteger(), nullable=False),
  sa.Column('pull_request_id', sa.BigInteger(), nullable=False),
  sa.Column('path', sa.Text(), nullable=False),
  sa.Column('previous_path', sa.Text(), nullable=True),
  sa.Column('status', sa.Text(), nullable=False),
  sa.Column('additions', sa.Integer(), nullable=False),
  sa.Column('deletions', sa.Integer(), nullable=False),
  sa.Column('changes', sa.Integer(), nullable=False),
  sa.Column('patch', sa.Text(), nullable=True),
  sa.Column('patch_size_bytes', sa.Integer(), nullable=True),
  sa.Column('patch_truncated', sa.Boolean(), nullable=False),
  sa.Column('blob_sha', sa.Text(), nullable=True),
  sa.Column('is_stale', sa.Boolean(), nullable=False),
  sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
  sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
  sa.PrimaryKeyConstraint('id'),
  sa.UniqueConstraint('pull_request_id', 'path')
  )
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('pull_request_files')
  op.drop_table('pull_requests')
  op.drop_table('github_events')
  op.drop_table('repositories')
  # ### end Alembic commands ###
